### ISSUE TITLE
HOW USE ‘$TPU_MODEL_DIR ’

### ISSUE THREAD

**Issue by Linij** [Paperspace/tpu-resnet#1]
HOW USE ‘$TPU_MODEL_DIR ’,
Has been prompt http code 403.
How do I use gcloud storage?

**Comment by dte** [comment]
Where are you receiving the error code? From our API or from Google?

**Comment by sanfilip** [comment]
$TPU_MODEL_DIR is an environment variable that points to a google storage bucket that is created and exists for the lifetime of a single Gradient job.  It is a URL with a scheme prefix of 'gs://', which is the format that most tensorflow TPU code expects.  The $TPU_MODEL_DIR can be written to by both the TPU and by code running on the Gradient job machine.  At the completion of the job the contents of that bucket are automatically uploaded to the Gradient jobs console in Paperspace.

You may encounter 403 errors if you use code that does not expect the 'gs://' prefix, or if you try to access the bucket after the job has completed.

If you could share the command that gave you the error and the full log output of the command we may be able to help debug further.

**Comment by Linij** [comment]
I've solved it.
You do need to configure the address and authorize it.
I suggest you can change it to local storage.
